import { Project } from "./types";

export const projects: Project[] = [
  {
    id: 1,
    title: "NepaStore",
    description:
      "B2B wholesale ordering platform. Contributed across frontend and backend — authentication, admin invitation flows, cart and order updates, audit support, and migration fixes using React, TypeScript, FastAPI, and PostgreSQL.",
    images: [
      "/images/projects/nepastore/admin-dashboard.jpg",
      "/images/projects/nepastore/admin-orders.jpg",
      "/images/projects/nepastore/admin-products.jpg",
      "/images/projects/nepastore/admin-storefront.jpg",
      "/images/projects/nepastore/browse-mob.jpg",
      "/images/projects/nepastore/browse-addtocart-mob.jpg",
      "/images/projects/nepastore/cart-mob.jpg",
      "/images/projects/nepastore/dashboard-mob.jpg",
      "/images/projects/nepastore/delivery-methods-mob.jpg",
      "/images/projects/nepastore/orders-mob.jpg",
      "/images/projects/nepastore/productsdetails-mob.jpg",
      "/images/projects/nepastore/productsdetails-relatedProducts-mob.jpg",
      "/images/projects/nepastore/productsdetails-youmaylike-mob.jpg",
    ],
    tags: ["React", "TypeScript", "FastAPI", "PostgreSQL", "Redis", "Docker"],
    category: "Full Stack",
  },
  {
    id: 2,
    title: "SellrClub",
    description:
      "Multi-tenant sales operations SaaS. Built password reset, workspace state management, notification integration, warehouse APIs, time-tracking support, and SMTP configuration across frontend and backend.",
    images: [
      "/images/projects/sellrclub/home.jpg",
      "/images/projects/sellrclub/workspaces.jpg",
      "/images/projects/sellrclub/products.jpg",
      "/images/projects/sellrclub/my inventory.jpg",
      "/images/projects/sellrclub/reports.jpg",
      "/images/projects/sellrclub/settings.jpg",
      "/images/projects/sellrclub/connectors.jpg",
      "/images/projects/sellrclub/routes.jpg",
      "/images/projects/sellrclub/data-pipeline.jpg",
      "/images/projects/sellrclub/auth-signin-signup.jpg",
      "/images/projects/sellrclub/bud-ai.jpg",
      "/images/projects/sellrclub/home-mob.jpg",
      "/images/projects/sellrclub/nav-mob.jpg",
      "/images/projects/sellrclub/products-mob.jpg",
      "/images/projects/sellrclub/reports-mob.jpg",
      "/images/projects/sellrclub/routes-mob.jpg",
      "/images/projects/sellrclub/connectors-mob.jpg",
      "/images/projects/sellrclub/data-pipeline-mob.jpg",
      "/images/projects/sellrclub/auth-signin-signup-mob.jpg",
      "/images/projects/sellrclub/bud-ai-mob.jpg",
      "/images/projects/sellrclub/active-visit-mob.jpg",
      "/images/projects/sellrclub/route-performance-mob.jpg",
      "/images/projects/sellrclub/my inventory-mob.jpg",
    ],
    tags: ["React", "TypeScript", "FastAPI", "PostgreSQL", "Redis", "Docker"],
    category: "SaaS",
  },
  {
    id: 3,
    title: "Homaale",
    description:
      "Service and product marketplace. Delivered backend APIs for booking slots, merchant workflows, payment integrations (Khalti, eSewa), analytics, and merchant-facing UI features including map and autocomplete flows.",
    images: [
      "/images/projects/homaale/homaale.com.jpg",
      "/images/projects/homaale/Homaale.com-ExplorePage.jpg",
      "/images/projects/homaale/homaale_category_page.jpg",
      "/images/projects/homaale/homaale_products_page.jpg",
      "/images/projects/homaale/homaale_merchant_page.jpg",
      "/images/projects/homaale/Homaale.com-TaskbookingPage.jpg",
      "/images/projects/homaale/Homaale.com-TaskbookingPage1.jpg",
      "/images/projects/homaale/Homaale.com-TaskDetailPage.jpg",
      "/images/projects/homaale/Homaale.com-loginPage.jpg",
      "/images/projects/homaale/Hoomale_feedback_page.jpg",
      "/images/projects/homaale/home-mob.jpg",
      "/images/projects/homaale/nav-mob.jpg",
      "/images/projects/homaale/category-mob.jpg",
      "/images/projects/homaale/products-mob.jpg",
      "/images/projects/homaale/merchant-mob.jpg",
      "/images/projects/homaale/services-mob.jpg",
      "/images/projects/homaale/quick-nav-mob.jpg",
      "/images/projects/homaale/account-settings-mob.jpg",
      "/images/projects/homaale/earnings-mob.jpg",
      "/images/projects/homaale/withdraw-mob.jpg",
    ],
    liveUrl: "https://homaale.com",
    tags: ["Next.js", "Django", "PostgreSQL", "REST API", "Pytest"],
    category: "Full Stack",
  },
  {
    id: 4,
    title: "Buzz API",
    description:
      "E-commerce and content backend with product CRUD, blog management, analytics APIs, vendor operations, cart and checkout improvements, Google OAuth, Khalti payments, and Redis caching.",
    images: ["/images/projects/buzz-api/buzz-api.jpg"],
    tags: ["Django", "PostgreSQL", "Redis", "REST API"],
    category: "Backend",
  },
  {
    id: 5,
    title: "MithoSweets",
    description:
      "E-commerce storefront for a traditional Nepali sweets brand. Contributed responsive UI updates, shop card improvements, best-seller slider refinements, and mobile experience fixes.",
    images: [
      "/images/projects/mithosweets/home.jpg",
      "/images/projects/mithosweets/shop.jpg",
      "/images/projects/mithosweets/about.jpg",
      "/images/projects/mithosweets/blog.jpg",
      "/images/projects/mithosweets/contact.jpg",
      "/images/projects/mithosweets/choose-us.jpg",
      "/images/projects/mithosweets/profile.jpg",
      "/images/projects/mithosweets/home-mob.jpg",
      "/images/projects/mithosweets/shop-mob.jpg",
      "/images/projects/mithosweets/about-mob.jpg",
      "/images/projects/mithosweets/blog-mob.jpg",
      "/images/projects/mithosweets/contact-mob.jpg",
      "/images/projects/mithosweets/choose-us-mob.jpg",
      "/images/projects/mithosweets/login-mob.jpg",
      "/images/projects/mithosweets/profile-mob.jpg",
    ],
    liveUrl: "https://mithosweets.com",
    tags: ["Next.js", "React", "Tailwind CSS"],
    category: "E-Commerce",
  },
  {
    id: 6,
    title: "CAGTU CMS",
    description:
      "Modular CMS and admin workspace used for content and operational management workflows across multiple CAGTU products.",
    images: ["/images/projects/cagtu-cms/cagtu-cms.jpg"],
    tags: ["Nx", "React", "Mantine", "React Query"],
    category: "CMS",
  },
];
