/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Pramil_3d_Grediant.glb --typescript --transform 
Files: Pramil_3d_Grediant.glb [19.12MB] > D:\Personal-Projects\portfolio\public\models\Pramil_3d_Grediant-transformed.glb [1.55MB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Pramil(props) {
  const { nodes, materials } = useGLTF('models/Pramil_3d_Grediant-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_5e3e2ad7-51de-428a-ab87-aa722cf2b7ab'].geometry} material={materials['tripo_mat_5e3e2ad7-51de-428a-ab87-aa722cf2b7ab']} />
    </group>
  )
}

useGLTF.preload('models/Pramil_3d_Grediant-transformed.glb')
